/* Ebb activity library — 60 tagged activities across mood 1-5.
   Voice: direct, concrete, short. No clinical jargon. No "research-backed."

   Shape: { id, text, instructions, why, category, mood_range, time_of_day, requires_daylight, benefit }
   - category: 'physical' | 'creative' | 'social' | 'spiritual'
   - time_of_day: subset of ['morning', 'afternoon', 'evening', 'late_night', 'any']
   - requires_daylight: true = filtered out past local sunset
   - benefit: 1 (light) | 2 (moderate) | 3 (strong)
*/

export const ACTIVITIES = [
  // ========== Mood 1 — rough ==========
  {
    id: 'cold_water_face',
    text: 'Cold water on your face.',
    instructions: 'Go to your sink. Run the water cold. Splash your face three times. That\'s it.',
    why: 'Works on your nervous system in seconds, not hours.',
    category: 'physical', mood_range: [1, 2], time_of_day: ['any'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'step_outside_60s',
    text: 'Outside for 60 seconds.',
    instructions: 'Open your door. Stand there. Look up. Come back in.',
    why: 'The inside of your head is the smallest room you\'re in right now.',
    category: 'physical', mood_range: [1, 2, 3], time_of_day: ['morning', 'afternoon', 'evening'], requires_daylight: true, benefit: 1,
  },
  {
    id: 'shake_it_out',
    text: 'Shake it out. Thirty seconds.',
    instructions: 'Stand. Shake your hands, arms, legs, face. Thirty seconds. Feel stupid, do it anyway.',
    why: 'Animals discharge stress physically. You stopped because someone told you to sit still.',
    category: 'physical', mood_range: [1, 2], time_of_day: ['any'], requires_daylight: false, benefit: 1,
  },
  {
    id: 'stretch_30s',
    text: 'Reach up for thirty seconds.',
    instructions: 'Interlace your fingers. Push your palms to the ceiling. Slow breath out at the top. Three rounds.',
    why: 'Your shoulders have been up near your ears for hours.',
    category: 'physical', mood_range: [1, 2, 3], time_of_day: ['any'], requires_daylight: false, benefit: 1,
  },
  {
    id: 'one_word',
    text: 'Name it in one word.',
    instructions: 'Open your notes. Type one word for how you feel. Don\'t explain. Don\'t punctuate.',
    why: 'You can\'t do anything about something you haven\'t named.',
    category: 'creative', mood_range: [1, 2, 3], time_of_day: ['any'], requires_daylight: false, benefit: 1,
  },
  {
    id: 'photo_closeup',
    text: 'One close-up photo.',
    instructions: 'Find something near you with texture you haven\'t really looked at. Take one photo. Look at it for a few seconds.',
    why: 'Attention outward breaks the loop.',
    category: 'creative', mood_range: [1, 2], time_of_day: ['any'], requires_daylight: false, benefit: 1,
  },
  {
    id: 'single_emoji',
    text: 'Send one emoji.',
    instructions: 'Pick a person who won\'t need an explanation. Send one emoji. You don\'t have to say more.',
    why: 'Connection doesn\'t require words you don\'t have.',
    category: 'social', mood_range: [1, 2], time_of_day: ['any'], requires_daylight: false, benefit: 1,
  },
  {
    id: 'old_message',
    text: 'Re-read one old message.',
    instructions: 'Find a conversation from someone who showed up for you before. Read a handful of messages. Don\'t reply.',
    why: 'Evidence that you\'re not imagining it.',
    category: 'social', mood_range: [1, 2], time_of_day: ['any'], requires_daylight: false, benefit: 1,
  },
  {
    id: 'four_seven_eight',
    text: 'Breathe: 4 in, 7 hold, 8 out. Three rounds.',
    instructions: 'In through your nose for 4. Hold for 7. Out through your mouth for 8. Three times.',
    why: 'A longer exhale tells your body the emergency is over.',
    category: 'spiritual', mood_range: [1, 2, 3], time_of_day: ['any'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'two_min_sit',
    text: 'Sit still for two minutes.',
    instructions: 'Set a timer. Phone face-down. Don\'t try to do anything. Two minutes.',
    why: 'Sometimes the move is to stop making moves.',
    category: 'spiritual', mood_range: [1, 2], time_of_day: ['any'], requires_daylight: false, benefit: 1,
  },
  {
    id: 'one_line',
    text: 'Read one line from something that grounds you.',
    instructions: 'A book, a verse, a note. One line. Read it twice.',
    why: 'An anchor doesn\'t have to be heavy.',
    category: 'spiritual', mood_range: [1, 2, 3], time_of_day: ['any'], requires_daylight: false, benefit: 1,
  },
  {
    id: 'five_things_see',
    text: 'Five things you can see right now.',
    instructions: 'Look around. Name five specific things out loud or in your head.',
    why: 'Panic shrinks the visual field. This expands it.',
    category: 'spiritual', mood_range: [1, 2], time_of_day: ['any'], requires_daylight: false, benefit: 1,
  },

  // ========== Mood 2 — low ==========
  {
    id: 'walk_5min',
    text: 'Walk to the end of your street and back.',
    instructions: 'Put on shoes. Walk out. Walk back. No destination, no pace.',
    why: 'Short movement counts. The bar is lower than you think.',
    category: 'physical', mood_range: [2, 3], time_of_day: ['morning', 'afternoon', 'evening'], requires_daylight: true, benefit: 2,
  },
  {
    id: 'tidy_one_surface',
    text: 'Clear one surface.',
    instructions: 'Pick one — desk, nightstand, counter. Five-minute timer. Stop when it rings.',
    why: 'One clear surface is an argument against the rest of the day.',
    category: 'physical', mood_range: [2, 3], time_of_day: ['morning', 'afternoon', 'evening', 'late_night'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'drink_water_slow',
    text: 'A full glass of water. Slowly.',
    instructions: 'Fill a glass. Sit down. Take 3-4 minutes to drink it.',
    why: 'You\'re probably dehydrated. It\'s boring and it works.',
    category: 'physical', mood_range: [2, 3], time_of_day: ['any'], requires_daylight: false, benefit: 1,
  },
  {
    id: 'warm_drink_slow',
    text: 'Make a warm drink. Drink it slowly.',
    instructions: 'Tea, warm water, broth — something warm. Don\'t multitask.',
    why: 'Warmth in your hands talks to your nervous system.',
    category: 'physical', mood_range: [1, 2, 3], time_of_day: ['evening', 'late_night'], requires_daylight: false, benefit: 1,
  },
  {
    id: 'three_words',
    text: 'Three words for today.',
    instructions: 'Open notes. Type three words. Not sentences. Not connected. Three honest words.',
    why: 'Journaling without the journal.',
    category: 'creative', mood_range: [2, 3], time_of_day: ['any'], requires_daylight: false, benefit: 1,
  },
  {
    id: 'one_song',
    text: 'One song. Nothing else.',
    instructions: 'Pick a song that doesn\'t sit heavy. Play it start to finish. Don\'t do anything else.',
    why: 'Music changes the room faster than thinking does.',
    category: 'creative', mood_range: [2, 3], time_of_day: ['any'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'rough_sketch',
    text: 'Sketch something you can see.',
    instructions: 'Pick an object near you. Draw it. Don\'t try to make it good.',
    why: 'Your hands aren\'t the problem. Thinking is the problem.',
    category: 'creative', mood_range: [2, 3], time_of_day: ['any'], requires_daylight: false, benefit: 1,
  },
  {
    id: 'text_small',
    text: 'Text one person one small thing.',
    instructions: 'Pick someone. Send something brief — "thinking of you," a meme, a question. No context required.',
    why: 'The bar is sending, not performing.',
    category: 'social', mood_range: [2, 3], time_of_day: ['any'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'warm_creator',
    text: 'One video from someone warm.',
    instructions: 'YouTube or TikTok. Pick one creator you trust. Watch one video. Close the app.',
    why: 'Parasocial doesn\'t replace, but it does register.',
    category: 'social', mood_range: [1, 2], time_of_day: ['any'], requires_daylight: false, benefit: 1,
  },
  {
    id: 'three_min_prayer',
    text: 'Three minutes of prayer or stillness.',
    instructions: 'Set a timer. Find a quiet spot. Pray, reflect, or hold one thing in mind.',
    why: 'Stillness on purpose is different from stillness by accident.',
    category: 'spiritual', mood_range: [2, 3], time_of_day: ['any'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'look_at_sky',
    text: 'Look at the sky for a minute.',
    instructions: 'Outside. Head up. Not the phone, not the people — the sky. One minute.',
    why: 'Big horizons settle small nervous systems.',
    category: 'spiritual', mood_range: [2, 3, 4], time_of_day: ['morning', 'afternoon', 'evening'], requires_daylight: true, benefit: 1,
  },
  {
    id: 'one_thing_happened',
    text: 'One thing that happened today.',
    instructions: 'Any sentence. "I made coffee" counts. Write it somewhere.',
    why: 'Writing one true sentence makes today real again.',
    category: 'spiritual', mood_range: [1, 2, 3], time_of_day: ['any'], requires_daylight: false, benefit: 1,
  },

  // ========== Mood 3 — okay ==========
  {
    id: 'walk_10min',
    text: 'Ten minutes walking outside.',
    instructions: 'Ten-minute timer. Walk any direction. Turn around when it rings.',
    why: 'The closest thing to an over-the-counter mood medication.',
    category: 'physical', mood_range: [3, 4], time_of_day: ['morning', 'afternoon', 'evening'], requires_daylight: true, benefit: 3,
  },
  {
    id: 'stretch_5min',
    text: 'Five minutes of stretching.',
    instructions: 'Neck, shoulders, forward fold. 20-30 seconds each. Breathe into the stretch.',
    why: 'Your body\'s been holding what your mind can\'t.',
    category: 'physical', mood_range: [3, 4, 5], time_of_day: ['any'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'real_meal',
    text: 'Make a real meal. Sit down.',
    instructions: 'Cook or prep something that isn\'t a snack. Sit away from screens to eat it.',
    why: '"Fuel" is a word food got stuck with. Eat like a person.',
    category: 'physical', mood_range: [3, 4, 5], time_of_day: ['morning', 'afternoon', 'evening'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'clean_one_dish',
    text: 'Wash one dish.',
    instructions: 'Just one. Not the sink. One dish.',
    why: 'The loop starts somewhere. Start here.',
    category: 'physical', mood_range: [2, 3], time_of_day: ['any'], requires_daylight: false, benefit: 1,
  },
  {
    id: 'short_nap',
    text: 'Twenty-minute nap.',
    instructions: 'Set an alarm for twenty minutes. Lie down. No phone. If you don\'t sleep, resting counts.',
    why: 'Sometimes the problem is sleep, not motivation.',
    category: 'physical', mood_range: [1, 2, 3], time_of_day: ['afternoon'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'one_win_specific',
    text: 'One specific thing that went okay today.',
    instructions: 'Be specific. "I sent that email" beats "I was productive." Write it down. Read it once.',
    why: '"Grateful for friends" is fog. Names and moments are data.',
    category: 'creative', mood_range: [3, 4, 5], time_of_day: ['any'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'creative_ten',
    text: 'Ten minutes on something creative. No judging.',
    instructions: 'Writing, drawing, editing, humming — pick one. Ten-minute timer. Rule: no evaluation until it rings.',
    why: 'Flow state is rented, not owned. Pay the rent.',
    category: 'creative', mood_range: [3, 4, 5], time_of_day: ['any'], requires_daylight: false, benefit: 3,
  },
  {
    id: 'real_convo',
    text: 'A real conversation. Voice, not text.',
    instructions: 'Call or meet someone. Ten minutes. Ask how they\'re actually doing. Listen to the answer.',
    why: 'Voice activates something text doesn\'t.',
    category: 'social', mood_range: [3, 4, 5], time_of_day: ['morning', 'afternoon', 'evening'], requires_daylight: false, benefit: 3,
  },
  {
    id: 'check_on_someone',
    text: 'Check in on someone else.',
    instructions: 'Pick someone who might be having a week. Ask how they are. Don\'t lead with your own stuff.',
    why: 'Pointing attention outward is its own medicine.',
    category: 'social', mood_range: [3, 4], time_of_day: ['any'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'say_no_to_one',
    text: 'Decline one thing you didn\'t want to do.',
    instructions: 'Send the message. "Can\'t this time" is a complete sentence.',
    why: 'Capacity is made by what you remove, not what you add.',
    category: 'social', mood_range: [2, 3, 4], time_of_day: ['any'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'read_paper_10',
    text: 'Ten minutes reading on paper.',
    instructions: 'Physical book or printed page. Ten-minute timer. When your mind wanders, find your place again.',
    why: 'The phone has trained your attention to flinch. Undo it a little.',
    category: 'spiritual', mood_range: [3, 4], time_of_day: ['any'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'showed_up',
    text: 'One moment today where you showed up.',
    instructions: 'Find one thing you did despite not wanting to. Say it out loud or write it down.',
    why: 'Credit yourself for things you wouldn\'t criticize a friend for skipping.',
    category: 'spiritual', mood_range: [3, 4, 5], time_of_day: ['any'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'three_breaths_window',
    text: 'Three slow breaths at a window.',
    instructions: 'Stand or sit near a window. Three breaths. Look at whatever\'s out there.',
    why: 'A window does half the work of going outside.',
    category: 'spiritual', mood_range: [1, 2, 3], time_of_day: ['any'], requires_daylight: false, benefit: 1,
  },

  // ========== Mood 4 — good ==========
  {
    id: 'walk_workout_20',
    text: 'Twenty minutes. Brisk.',
    instructions: 'Walk fast, run, or move your heart rate up. Push a little past comfortable.',
    why: 'Capacity is highest when mood is. Use it.',
    category: 'physical', mood_range: [4, 5], time_of_day: ['morning', 'afternoon', 'evening'], requires_daylight: true, benefit: 3,
  },
  {
    id: 'cook_scratch',
    text: 'Cook something from scratch.',
    instructions: 'Real ingredients. At least twenty minutes of effort. Eat it without your phone.',
    why: 'Building something edible is an act of care you can taste.',
    category: 'physical', mood_range: [4, 5], time_of_day: ['morning', 'afternoon', 'evening'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'morning_sun',
    text: 'Ten minutes of morning sun.',
    instructions: 'Outside within an hour of waking. No sunglasses. No glass in between. Ten minutes.',
    why: 'The signal that tells your body what time it is.',
    category: 'physical', mood_range: [3, 4, 5], time_of_day: ['morning'], requires_daylight: true, benefit: 3,
  },
  {
    id: 'walk_without_phone',
    text: 'Walk without the phone.',
    instructions: 'Leave it behind. Fifteen minutes out the door.',
    why: 'The urge to fill silence is the point.',
    category: 'physical', mood_range: [3, 4, 5], time_of_day: ['morning', 'afternoon', 'evening'], requires_daylight: true, benefit: 2,
  },
  {
    id: 'putoff_project_20',
    text: 'Twenty minutes on the thing you\'ve been avoiding.',
    instructions: 'The one you keep pushing. Twenty-minute timer. Start — don\'t plan.',
    why: 'Avoidance is heaviest when mood is low. Lift it now.',
    category: 'creative', mood_range: [4, 5], time_of_day: ['morning', 'afternoon', 'evening'], requires_daylight: false, benefit: 3,
  },
  {
    id: 'share_small_creation',
    text: 'Make something small. Send it to one person.',
    instructions: 'Doesn\'t have to be finished. Doesn\'t need explanation. "made this" is the whole message.',
    why: 'Creative vulnerability costs less at mood 4 than at mood 2.',
    category: 'creative', mood_range: [4, 5], time_of_day: ['any'], requires_daylight: false, benefit: 3,
  },
  {
    id: 'start_curiosity',
    text: 'Start something you\'ve been curious about.',
    instructions: 'Twenty minutes. Not research — the first step of actually doing it.',
    why: 'Curiosity is cheap until you act on it.',
    category: 'creative', mood_range: [4, 5], time_of_day: ['any'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'handwritten_note',
    text: 'Write a note by hand.',
    instructions: 'To someone. About anything. Mail it or save it. The hand part matters.',
    why: 'Different part of the brain. Different kind of attention.',
    category: 'creative', mood_range: [3, 4, 5], time_of_day: ['any'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'reach_out_old',
    text: 'Reach out to someone you\'ve lost touch with.',
    instructions: 'A real message — not "hey." Reference a memory or ask a specific question.',
    why: 'The relationships you maintain at 4 are the ones there at 2.',
    category: 'social', mood_range: [4, 5], time_of_day: ['any'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'quiet_kindness',
    text: 'One kind thing for someone. Don\'t mention it.',
    instructions: 'Small, genuine, unasked-for. Don\'t tell them you did it.',
    why: 'Generosity without receipt changes the giver more.',
    category: 'social', mood_range: [4, 5], time_of_day: ['any'], requires_daylight: false, benefit: 3,
  },
  {
    id: 'gratitude_specific',
    text: 'Fifteen minutes: prayer, reflection, or journal.',
    instructions: 'Pick one. Set a timer. Name specific people, moments, things. Don\'t rush it.',
    why: 'Abstract gratitude is a habit. Specific gratitude is a practice.',
    category: 'spiritual', mood_range: [4, 5], time_of_day: ['any'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'what_helped',
    text: 'What specifically helped today?',
    instructions: 'Times, people, actions. Write down what contributed to today being okay.',
    why: 'You\'re building your own map. You\'ll need it at mood 2.',
    category: 'spiritual', mood_range: [4, 5], time_of_day: ['evening', 'late_night'], requires_daylight: false, benefit: 3,
  },

  // ========== Mood 5 — great ==========
  {
    id: 'push_physical',
    text: 'Push. Run something new.',
    instructions: 'New route, heavier weight, longer distance. High mood means high capacity. Spend some.',
    why: 'Your body remembers what it can do. Remind it.',
    category: 'physical', mood_range: [5], time_of_day: ['morning', 'afternoon', 'evening'], requires_daylight: true, benefit: 3,
  },
  {
    id: 'try_new_physical',
    text: 'Try a physical thing you\'ve been curious about.',
    instructions: 'A sport, a class, a trail. Today\'s the day. Make it concrete.',
    why: 'Novelty at peak state builds confidence for flat days.',
    category: 'physical', mood_range: [5], time_of_day: ['morning', 'afternoon', 'evening'], requires_daylight: false, benefit: 3,
  },
  {
    id: 'hardest_creative',
    text: 'The creative thing you\'re delaying. Start the hardest part.',
    instructions: 'Name the project. Open what it needs. Start with what scares you. Thirty minutes.',
    why: 'The hardest part gets lighter than it\'ll ever be.',
    category: 'creative', mood_range: [5], time_of_day: ['any'], requires_daylight: false, benefit: 3,
  },
  {
    id: 'teach_something',
    text: 'Teach one thing you know well.',
    instructions: 'Pick someone who could use it. Offer a conversation, a message, a video — specific and concrete.',
    why: 'Teaching is how understanding ossifies.',
    category: 'creative', mood_range: [4, 5], time_of_day: ['any'], requires_daylight: false, benefit: 3,
  },
  {
    id: 'release_something',
    text: 'Release something you made.',
    instructions: 'Post it, send it, share it. Even unfinished. Releasing is the skill.',
    why: 'Things unreleased don\'t exist. The act of sending is the work.',
    category: 'creative', mood_range: [5], time_of_day: ['any'], requires_daylight: false, benefit: 3,
  },
  {
    id: 'deepen_convo',
    text: 'Go past small talk with someone.',
    instructions: 'Reach out. Ask something specific about their life you\'ve actually wondered about. Stay long enough.',
    why: 'Depth is built when it\'s easy so it\'s available when it\'s not.',
    category: 'social', mood_range: [4, 5], time_of_day: ['any'], requires_daylight: false, benefit: 3,
  },
  {
    id: 'plan_something',
    text: 'Make concrete plans with one person.',
    instructions: 'Date. Time. Place. Today. Doesn\'t have to be elaborate.',
    why: 'Anticipation is a mood-stabilizer you can schedule.',
    category: 'social', mood_range: [4, 5], time_of_day: ['any'], requires_daylight: false, benefit: 2,
  },
  {
    id: 'what_working',
    text: 'Ten minutes: what\'s been working and why?',
    instructions: 'Write. Specific. Name the habits, the people, the decisions. You\'re making evidence.',
    why: 'You will try to revise this story downward later. Capture it now.',
    category: 'spiritual', mood_range: [4, 5], time_of_day: ['any'], requires_daylight: false, benefit: 3,
  },
  {
    id: 'unexpected_service',
    text: 'Something meaningful for someone who doesn\'t expect it.',
    instructions: 'Think of someone who expects nothing from you right now. Give generously, from abundance.',
    why: 'Give when you can spare it. That\'s all it means.',
    category: 'spiritual', mood_range: [5], time_of_day: ['any'], requires_daylight: false, benefit: 3,
  },
  {
    id: 're_read_past_self',
    text: 'Re-read something you wrote at a lower mood.',
    instructions: 'Find an old note, entry, or message. Read it with today\'s brain.',
    why: 'The version of you writing now will help the next one.',
    category: 'spiritual', mood_range: [4, 5], time_of_day: ['any'], requires_daylight: false, benefit: 2,
  },
];

export function byId(id) {
  return ACTIVITIES.find(a => a.id === id) || null;
}
